
language: python
python:
  - 3.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - gh release download z3_solver-4.8.12.0-py2.py3-none-manylinux1_x86_64.whl
#   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - sudo apt-get update
#   - sudo apt-get install g++-7
#   - git clone https://github.com/Z3Prover/z3.git
#   - cd z3
#   - python3 scripts/mk_make.py --python
#   - cd build
#   - g++ --version
#   - g++ -std=c++17 -o testcode1 ../src/shell/gparams_register_modules.cpp
#   - make
#   - sudo make install
  - ls .
  - cd ..
  - ls .
  - cd fall-2021/project
  - python -m unittest formula_gen_tests.py
 
deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDk3YmU3Y2M2LWI3ZjgtNDlmYy1iYzc2LTBjMjgyZjYzMjEwNQACQnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJmb3JtdWxhLWdlbmVyYXRvciJdfSwgInZlcnNpb24iOiAxfQAABiANze9G3FuFSAZ6jbFmZRDXiUZCyKLd0VqH-slrRzKaLw"
  on:
    branch: main
